[package]
name = "abc215"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = "*"
itertools = "*"
foreach = "*"
[profile.release]
lto = true
panic = 'abort'
